name: Quality
on:
  push:
    branches: [ feature_oquare_metrics ]
    paths:
      - 'development/**'
      - 'robot/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'development/**'
      - 'robot/**'

jobs:
  robot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: RobotReport
      run: make quality --directory ./robot
  oquare:
    runs-on: ubuntu-latest
    name: OQuaRE-metrics-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: OQuaREReport
        uses: tecnomod-um/oquare-metrics@v3.0
        with:
          ontology-folders: development
          contents-folder: oquare
