on:
  push:
    branches: [ feature_oquare_metrics ]
    paths:
      - 'development/**'
      - 'robot/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'development/**'
      - 'robot/**'

jobs:
  robot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Report
      run: make quality --directory ./robot
      
