name: Makefile CI

on:
  push:
    branches: [ feature_robot_report ]
    paths:
      - 'development/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'development/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Report
      run: make report --directory ./robot
      
